use crate::core::result::AttackSummary;

#[allow(dead_code)]
pub fn generate_html_report(summary: &AttackSummary) -> String {
    let duration_str = summary.total_duration
        .map(|d| format!("{:.2}s", d.as_secs_f64()))
        .unwrap_or_else(|| "N/A".to_string());

    let success_rows: String = summary.results.iter()
        .filter(|r| r.success)
        .map(|r| format!(
            "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
            r.target_host,
            r.target_port,
            r.protocol,
            r.username,
            r.password,
            r.timestamp.format("%Y-%m-%d %H:%M:%S"),
            r.duration_ms,
        ))
        .collect::<Vec<_>>()
        .join("\n");

    let fail_rows: String = summary.results.iter()
        .filter(|r| !r.success)
        .map(|r| format!(
            "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
            r.target_host,
            r.target_port,
            r.protocol,
            r.username,
            r.password,
            r.error.as_deref().unwrap_or("Auth failed"),
        ))
        .collect::<Vec<_>>()
        .join("\n");

    format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Veltrix Attack Report</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 20px; background: #0d1117; color: #c9d1d9; }}
  h1, h2, h3 {{ color: #58a6ff; }}
  .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin: 20px 0; }}
  .stat {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px; text-align: center; }}
  .stat .value {{ font-size: 2em; font-weight: bold; }}
  .stat .label {{ color: #8b949e; font-size: 0.85em; text-transform: uppercase; }}
  .stat.success .value {{ color: #3fb950; }}
  .stat.fail .value {{ color: #f85149; }}
  .stat.error .value {{ color: #d29922; }}
  table {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
  th, td {{ border: 1px solid #30363d; padding: 8px 12px; text-align: left; }}
  th {{ background: #161b22; color: #58a6ff; }}
  tr:nth-child(even) {{ background: #161b22; }}
  .success-row {{ color: #3fb950; }}
  .fail-row {{ color: #f85149; }}
  .footer {{ margin-top: 32px; color: #8b949e; font-size: 0.85em; text-align: center; }}
</style>
</head>
<body>
<h1>🔐 Veltrix Attack Report</h1>
<div class="summary">
  <div class="stat success"><div class="value">{}</div><div class="label">Successes</div></div>
  <div class="stat fail"><div class="value">{}</div><div class="label">Failures</div></div>
  <div class="stat error"><div class="value">{}</div><div class="label">Errors</div></div>
  <div class="stat"><div class="value">{}</div><div class="label">Targets</div></div>
  <div class="stat"><div class="value">{}</div><div class="label">Credentials</div></div>
  <div class="stat"><div class="value">{}</div><div class="label">Duration</div></div>
</div>

<h2>✅ Successes ({} found)</h2>
<table>
<thead><tr><th>Host</th><th>Port</th><th>Protocol</th><th>Username</th><th>Password</th><th>Timestamp</th><th>ms</th></tr></thead>
<tbody>{}
</tbody></table>

<h2>❌ Failures ({} shown)</h2>
<table>
<thead><tr><th>Host</th><th>Port</th><th>Protocol</th><th>Username</th><th>Password</th><th>Error</th></tr></thead>
<tbody>{}
</tbody></table>

<div class="footer">
  Generated by Veltrix v1.0.0 |
  Started: {} |
  Total attempts: {}
</div>
</body>
</html>"#,
        summary.successes,
        summary.failures,
        summary.errors,
        summary.total_targets,
        summary.total_credentials,
        duration_str,
        summary.successes,
        success_rows,
        std::cmp::min(summary.results.iter().filter(|r| !r.success).count(), 100),
        fail_rows,
        summary.start_time.format("%Y-%m-%d %H:%M:%S"),
        summary.attempts,
    )
}
